version: 2.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: saramohamed2010
          password: $26091992SaraDocker  # context / project UI env-var reference
    steps:
       - build
       - run: -mvn clean test

  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: saramohamed2010
          password: $26091992SaraDocker  # context / project UI env-var reference
    steps:
      - build
      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build